// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatSubscriptionController from "./chat_subscription_controller.js"
application.register("chat-subscription", ChatSubscriptionController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import SendOnEnterController from "./send_on_enter_controller.js"
application.register("send-on-enter", SendOnEnterController)

import VideoCallController from "./video_call_controller.js"
application.register("video-call", VideoCallController)
